# Generated by Django 5.2.3 on 2025-06-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Jobseeker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resume', models.TextField(blank=True)),
                ('dateSent', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('interviewDate', models.DateTimeField(blank=True, null=True)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.job')),
                ('employerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_posts', to='app.user')),
                ('jobSeekerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_posts', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('startDate', models.DateTimeField()),
                ('expiryDate', models.DateTimeField()),
                ('transactionId', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='employerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='app.user'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.job')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.user')),
            ],
        ),
    ]
